### ISSUE TITLE
'.' is not recognized and flow is not recognized

### ISSUE THREAD

**Issue by stanleyshly** [llSourcell/YOLO_Object_Detection#11]
I use windows.  I  typed flow --h, and the alternatives, but it say flow is not recognized as a internal or external command.  I have pip install flow and the other cython, opencv, numpy , etc libraries.

**Comment by bermudezarii** [comment]
Same here ): HELP!

**Comment by bermudezarii** [comment]
Use this: 
`python flow --h`

**Comment by shreyaspimpalgaonkar** [comment]
I got the following error on typing this
    python flow --h

Error is : 

    Traceback (most recent call last):
      File "flow", line 4, in <module>
        from darkflow.cli import cliHandler
      File "D:\YOLO_Object_Detection\darkflow\cli.py", line 3, in <module>
        from .net.build import TFNet
      File "D:\YOLO_Object_Detection\darkflow\net\build.py", line 7, in <module>
        from .framework import create_framework
      File "D:\YOLO_Object_Detection\darkflow\net\framework.py", line 1, in <module>
        from . import yolo
      File "D:\YOLO_Object_Detection\darkflow\net\yolo\__init__.py", line 2, in <module>
        from . import predict
      File "D:\YOLO_Object_Detection\darkflow\net\yolo\predict.py", line 7, in <module>
        from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
      File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.cython_utils.cy_yolo_findboxes
        import numpy as np
    ModuleNotFoundError: No module named 'nms'
