### ISSUE TITLE
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

### ISSUE THREAD

**Issue by ithjz** [llSourcell/YOLO_Object_Detection#5]
Traceback (most recent call last):
  File "D:\Users\Administrator\workspace\YOLO_Object_Detection-master\test\test_darkflow.py", line 1, in <module>
    from darkflow.net.build import TFNet
  File "D:\Users\Administrator\workspace\YOLO_Object_Detection-master\darkflow\net\build.py", line 7, in <module>
    from .framework import create_framework
  File "D:\Users\Administrator\workspace\YOLO_Object_Detection-master\darkflow\net\framework.py", line 1, in <module>
    from . import yolo
  File "D:\Users\Administrator\workspace\YOLO_Object_Detection-master\darkflow\net\yolo\__init__.py", line 2, in <module>
    from . import predict
  File "D:\Users\Administrator\workspace\YOLO_Object_Detection-master\darkflow\net\yolo\predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

**Comment by lg0killer** [comment]
Try this page for Windows:
http://iam-data.com/resolving-python-error-fix-link-fatal-error-lnk1158-cannot-run-rcexe

**Comment by sjhansen3** [comment]
Advice for similar issue on Mac?

Warning: Extension name 'darkflow.cython_utils.nms' does not match fully qualified name 'nms' of 'darkflow/cython_utils/nms.pyx'
Warning: Extension name 'darkflow.cython_utils.cy_yolo2_findboxes' does not match fully qualified name 'cy_yolo2_findboxes' of 'darkflow/cython_utils/cy_yolo2_findboxes.pyx'
darkflow/cython_utils/cy_yolo2_findboxes.pyx: cannot find cimported module 'nms'
Warning: Extension name 'darkflow.cython_utils.cy_yolo_findboxes' does not match fully qualified name 'cy_yolo_findboxes' of 'darkflow/cython_utils/cy_yolo_findboxes.pyx'
darkflow/cython_utils/cy_yolo_findboxes.pyx: cannot find cimported module 'nms'
running build_ext
copying build/lib.macosx-10.6-intel-3.6/darkflow/cython_utils/nms.cpython-36m-darwin.so -> darkflow/cython_utils
copying build/lib.macosx-10.6-intel-3.6/darkflow/cython_utils/cy_yolo2_findboxes.cpython-36m-darwin.so -> darkflow/cython_utils
copying build/lib.macosx-10.6-intel-3.6/darkflow/cython_utils/cy_yolo_findboxes.cpython-36m-darwin.so -> darkflow/cython_utils

**Comment by skylinetech-team** [comment]
seeing same error on Mac Air, any advises ?

 File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

**Comment by Louagyd** [comment]
you should run the script inside darkflow folder.

**Comment by vaibhavshukla182** [comment]
trying installing dark flow globally using pip install -e. 
it worked for me
