### ISSUE TITLE
ImportError: No module named 'nms'

### ISSUE THREAD

**Issue by rahard** [llSourcell/YOLO_Object_Detection#7]
running
   flow --h
produces:
ImportError: No module named 'nms'

**Comment by marlon-rodrigues** [comment]
@rahard This solved for me: https://keponk.wordpress.com/2017/12/07/siraj-darkflow/

**Comment by BillCai06** [comment]
The same problem here, after following the post, it is running in the miniconda with py3.6.3 and cython. I tried many times with a fresh clone, still got No module named 'nms' even after running it with weights and cfg

**Comment by rahard** [comment]
marlon, I will check the link ... thanks
(meanwhile - on a different thread - I got darknet running using the code from darknet's site. at least I can reproduce YOLO.)

**Comment by BillCai06** [comment]
Thank you rahard,  The code from https://github.com/thtrieu/darkflow has no such error. It run with out any problems

**Comment by glaizaavila** [comment]
Hi! I am also having this problem. How about if my tensorflow is not in GPU version, just CPU, what should be done to solve the problem?

**Comment by skylinetech-team** [comment]
hi, I am running on mac air with tensor flow activated
./flow --h
got the following errors, any advises ? thanks much !

(tensorflow) Marks-MacBook-Air:YOLO_Object_Detection markhu$ ./flow --h
/Users/markhu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/Users/markhu/Projects/object_detection_frameworks/YOLO_Object_Detection/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
  File "darkflow/cython_utils/cy_yolo_findboxes.pyx", line 1, in init cy_yolo_findboxes
    import numpy as np
ModuleNotFoundError: No module named 'nms'

**Comment by skylinetech-team** [comment]
also tried https://github.com/thtrieu/darkflow, got same error

**Comment by carlchandev** [comment]
I am a mac user and using python 3.6 on anaconda and i got the same problem as well. I have tried googled it with no luck. Did anyone found a solution?

**Comment by KingfaLuis** [comment]
Traceback (most recent call last):
  File "G:/workspace/PycharmProjects/py_hog_svm/py_03_hog_feature.py", line 10, in <module>
    from get_data import get_pos_samples, get_neg_samples, read_pos_samples, read_neg_samples
ModuleNotFoundError: No module named 'get_data'

**Comment by Mohammed-Shoaib** [comment]
Same issue. No module named 'nms'.

Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\cli.py", line 3,
in <module>
    from .net.build import TFNet
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\build.py", li
ne 7, in <module>
    from .framework import create_framework
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\framework.py"
, line 1, in <module>
    from . import yolo
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\__init__
.py", line 2, in <module>
    from . import predict
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\predict.
py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
  File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.c
ython_utils.cy_yolo_findboxes
    import numpy as np
ModuleNotFoundError: No module named 'nms'

>python flow --h
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\cli.py", line 3,
in <module>
    from .net.build import TFNet
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\build.py", li
ne 7, in <module>
    from .framework import create_framework
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\framework.py"
, line 1, in <module>
    from . import yolo
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\__init__
.py", line 2, in <module>
    from . import predict
  File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\predict.
py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
  File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.c
ython_utils.cy_yolo_findboxes
    import numpy as np
ModuleNotFoundError: No module named 'nms'

Please can someone help resolve this issue?

**Comment by Casp3rBB** [comment]
> Same issue. No module named 'nms'.
> 
> Traceback (most recent call last):
> File "flow", line 4, in 
> from darkflow.cli import cliHandler
> File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\cli.py", line 3,
> in 
> from .net.build import TFNet
> File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\build.py", li
> ne 7, in 
> from .framework import create_framework
> File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\framework.py"
> , line 1, in 
> from . import yolo
> File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo__init__
> .py", line 2, in 
> from . import predict
> File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\predict.
> py", line 7, in 
> from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
> File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.c
> ython_utils.cy_yolo_findboxes
> import numpy as np
> ModuleNotFoundError: No module named 'nms'
> 
> > python flow --h
> > Traceback (most recent call last):
> > File "flow", line 4, in 
> > from darkflow.cli import cliHandler
> > File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\cli.py", line 3,
> > in 
> > from .net.build import TFNet
> > File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\build.py", li
> > ne 7, in 
> > from .framework import create_framework
> > File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\framework.py"
> > , line 1, in 
> > from . import yolo
> > File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo__init__
> > .py", line 2, in 
> > from . import predict
> > File "C:\Users\Shoaib\Desktop\YOLO_Object_Detection\darkflow\net\yolo\predict.
> > py", line 7, in 
> > from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
> > File "darkflow\cython_utils\cy_yolo_findboxes.pyx", line 1, in init darkflow.c
> > ython_utils.cy_yolo_findboxes
> > import numpy as np
> > ModuleNotFoundError: No module named 'nms'
> 
> Please can someone help resolve this issue?

Same issue here, when I pip install nms, i got error "AttributeError: module 'nms' has no attribute '__pyx_capi__'

**Comment by ArghyaChatterjee** [comment]
just go to the actual link [https://github.com/thtrieu/darkflow](https://github.com/thtrieu/darkflow). Download the files, delete the previous ones manually and run the commands one by one. I guess it should work now.

**Comment by FossilDaddy** [comment]
I used the first way to install the darflow and I had the same problem in the beginning, but later I solve it by use
![image](https://user-images.githubusercontent.com/37012127/54183003-fc211b00-44dd-11e9-8e90-9b0d72b0e0f8.png)
